// <auto-generated />

namespace DbControlCore.Models
{
    public class ConfigModel
    {
        public string Name { get; set; }

        public string Connection { get; set; }

        public bool IsEnabled { get; set; }
    }
}
